source 'https://github.com/wgModularization/WGModulSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'WGXibPersonKit_Example' do
  pod 'WGXibPersonKit', :path => '../'

  target 'WGXibPersonKit_Tests' do
    inherit! :search_paths

    
  end
end
